#!/usr/bin/env bash

# https://github.com/adnanh/webhook/

docker run \
	-d \
	--restart=unless-stopped \
	-p 9090:9000 \
	-v $HOME/DockerData/webhook:/etc/webhook almir/webhook \
	-hooks /etc/webhook/${1:-"hooks.json"} \
	-hotreload \
	-verbose \
	-nopanic
