#!/usr/bin/env bash

set -e;
REAL_SOURCE="$(realpath ./)";
ORIG_PWD="$(pwd)";


for s in $REAL_SOURCE/src/*; do
	if [ -e $s/build.sh ]; then
		cd $s;
		bash $s/build.sh;
	fi
	cd $ORIG_PWD;
done

SHIM_DEST="$HOME/bin";
if [ ! -d $SHIM_DEST ]; then
	mkdir -p $SHIM_DEST;
fi

for f in $REAL_SOURCE/shims/*; do
	chmod +x $f;
	filename="${f##*/}";
	if [ ! -e $SHIM_DEST/$filename ]; then
		echo "Creating shim for $filename";
		ln -s $f $SHIM_DEST/$filename;
	fi
done
